name: Deploy to Easyname via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: e133904-ftp.services.easyname.eu
          username: 202249ftp1
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /html/karohilft-neu/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
